# Generated by Django 2.2.1 on 2019-06-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=225, verbose_name='First name')),
                ('last_name', models.CharField(max_length=225, verbose_name='Last name')),
                ('position', models.CharField(max_length=225, verbose_name='Position')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('reviewer', models.BooleanField(default=False, verbose_name='Reviewer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
