# Generated by Django 2.2.1 on 2019-05-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='Admin', max_length=225, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
