# Generated by Django 2.2.1 on 2019-06-10 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_place', models.CharField(choices=[('PIH Haiti', 'PIH Haiti'), ('PIH Kazakhstan', 'PIH Kazakhstan'), ('PIH Lesotho', 'PIH Lesotho'), ('PIH Liberia', 'PIH Liberia'), ('PIH Malawi', 'PIH Malawi'), ('PIH Mexico', 'PIH Mexico'), ('PIH Navajo', 'PIH Navajo'), ('PIH Peru', 'PIH Peru'), ('PIH Rwanda', 'PIH Rwanda'), ('PIH Sierra Leone', 'PIH Sierra Leone'), ('other', 'Other')], max_length=225, verbose_name='Place of Departure')),
                ('other_place', models.CharField(blank=True, max_length=225, null=True, verbose_name='Other Place of Departure (please specify)')),
                ('purpose', models.TextField(max_length=1000, verbose_name='Purpose of Visit')),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Submitted on')),
                ('num_visitors', models.IntegerField(verbose_name='Number of Visitors')),
                ('review_comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Review comment')),
                ('status', models.CharField(choices=[('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='review', max_length=225)),
                ('review_date', models.DateField(verbose_name='Reviewed on')),
                ('host', models.ForeignKey(blank=True, default=None, null=True, on_delete='SET_DEFAULT', to=settings.AUTH_USER_MODEL, verbose_name='Requestor/Host')),
                ('reviewer', models.ForeignKey(blank=True, default=None, null=True, on_delete='SET_DEFAULT', related_name='reviewer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Full name of Visitor')),
                ('request_form', models.ForeignKey(on_delete='CASCADE', to='pih_app.Request', verbose_name='Request')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Flights', 'Flights'), ('Visa', 'Visa'), ('Accommodation', 'Accommodation'), ('Transport', 'Transport'), ('Seacoach', 'Seacoach'), ('Other', 'Other')], max_length=225)),
                ('organized_by_us', models.BooleanField(default=False, verbose_name='Organized by us?')),
                ('expenses_covered_by', models.CharField(choices=[('Entirely by visitor', 'Entirely by visitor'), ('Covered by us but reimbursed', 'Covered by us but reimbursed'), ('Covered by us (not reimbursed)', 'Covered by us (not reimbursed)')], max_length=225, verbose_name='Expenses covered by')),
                ('expenses_amount', models.IntegerField(blank='True', null=True, verbose_name='Estimated expenses amount in USD')),
                ('notes', models.TextField(blank=True, max_length=225, null=True, verbose_name='Additional Notes')),
                ('is_organized', models.BooleanField(default=False, verbose_name='Has been organized')),
                ('expense_paid', models.BooleanField(default=False, verbose_name='Expense has been paid')),
                ('marked_as_paid_on', models.DateField(blank=True, null=True, verbose_name='Marked as paid on')),
                ('expense_reimbursed', models.BooleanField(default=False, verbose_name='Expense has been reimbursed')),
                ('marked_as_reimbursed_on', models.DateField(blank=True, null=True, verbose_name='Marked as reimbursed on')),
                ('marked_as_paid_by', models.ForeignKey(blank=True, default=None, null=True, on_delete='SET_DEFAULT', related_name='marked_as_paid_by', to=settings.AUTH_USER_MODEL, verbose_name='Marked as paid by')),
                ('marked_as_reimbursed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete='SET_DEFAULT', related_name='marked_as_reimbursed_by', to=settings.AUTH_USER_MODEL, verbose_name='Marked as reimbursed by')),
                ('name_of_organizer', models.ForeignKey(blank=True, default=None, null=True, on_delete='SET_DEFAULT', to=settings.AUTH_USER_MODEL, verbose_name='Name of Organizer')),
                ('request_form', models.ForeignKey(on_delete='CASCADE', to='pih_app.Request', verbose_name='Request')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
