# Generated by Django 2.2.1 on 2019-06-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pih_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_reimbursed',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Amount reimbursed'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expenses_amount',
            field=models.FloatField(blank='True', null=True, verbose_name='Estimated expenses amount in USD'),
        ),
    ]
