# Generated by Django 2.2.1 on 2019-06-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pih_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Reviewed on'),
        ),
    ]
