# Generated by Django 2.2.1 on 2019-06-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pih_app', '0002_auto_20190610_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-submission_date']},
        ),
        migrations.AlterModelManagers(
            name='expense',
            managers=[
            ],
        ),
    ]
