# Generated by Django 2.2.2 on 2019-07-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pih_app", "0002_auto_20190619_0655")]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="review_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Reviewed on"
            ),
        )
    ]
