# Generated by Django 2.2.1 on 2019-06-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pih_app', '0003_auto_20190610_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_paid',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='marked_as_paid_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='marked_as_paid_on',
        ),
    ]
